---
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplephone
  namespace: production
spec:
  selector:
    matchLabels:
      run: simplephone
  template:
    metadata:
      labels:
        run: simplephone
    spec:
      containers:
      - name: simplephone
        image: phantasm/simplephone:8b3bc2adb62dee5c3ef554238d363d9cabef8b0c
        imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: 80
        env:
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: simplephone
              key: password
        - name: DB_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: simplephone
              key: db_endpoint
        - name: API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: simplephone
              key: api_secret_key
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
