---
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplephone
  namespace: production
spec:
  selector:
    matchLabels:
      run: simplephone
  template:
    metadata:
      labels:
        run: simplephone
    spec:
      containers:
      - name: simplephone
        image: phantasm/simplephone:V20220802_0_01
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: simplephone
              key: password
        - name: DB_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: simplephone
              key: db_endpoint
        - name: API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: simplephone
              key: api_secret_key
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
