apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplephone
  namespace: production
spec:
  selector:
    matchLabels:
      run: simplephone
  template:
    metadata:
      labels:
        run: simplephone
    spec:
      containers:
      # - name: nginx
      #   image: phantasm/nginx-sidecar:269e4ee1345cc777af115fb76169362afa5a26dc
      #   imagePullPolicy: IfNotPresent
      #   livenessProbe:
      #     httpGet:
      #       path: /static/css/bootstrap.min.css
      #       port: 80
      #   ports:
      #   - containerPort: 80
      #     protocol: TCP
      #   resources:
      #     limits:
      #       cpu: 200m
      #       memory: 256Mi
      #     requests:
      #       cpu: 200m
      #       memory: 256Mi
      - name: simplephone
        image: phantasm/simplephone:68c09c563926a4ff4551e16624c0676cb0d66899
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        envFrom:
        - secretRef:
            name: simplephone
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
