---
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplephone
  namespace: production
spec:
  selector:
    matchLabels:
      run: simplephone
  template:
    metadata:
      labels:
        run: simplephone
    spec:
      containers:
      - name: nginx
        image: phantasm/nginx-sidecar:66b45f681c6c7c0d9136c29214893e535f43a77e
        imagePullPolicy: IfNotPresent
        # livenessProbe:
        #   httpGet:
        #     path: /static/css/bootstrap.min.css
        #     port: 80
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
      - name: simplephone
        image: phantasm/simplephone:66b45f681c6c7c0d9136c29214893e535f43a77e
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: 5000
        env:
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: simplephone
              key: password
        - name: DB_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: simplephone
              key: db_endpoint
        - name: API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: simplephone
              key: api_secret_key
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
