---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: simplephone
  namespace: production
spec:
  hard:
    pods: 10
    requests.cpu: 6
    requests.memory: 10Gi
    limits.cpu: 10
    limits.memory: 10Gi
