---
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: v1
kind: Secret
metadata:
  name: simplephone
  namespace: production
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASSWORD: ZGV2
  DB_HOSTNAME: bXlzcWwucHJvZHVjdGlvbi5zdmMuY2x1c3Rlci5sb2NhbA==
  API_SECRET_KEY: c2VjdXJlLWFwaS1zZWNyZXQ=
  MYSQL_ROOT_PASSWORD: ZGV2