---
apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: v1
kind: Secret
metadata:
  name: simplephone
  namespace: production
type: kubernetes.io/basic-auth
stringData:
# These credentials are only use on local development cluster(kind) 
  username: root
  password: dev
  db_endpoint: mysql.production.svc.cluster.local
  api_secret_key: secure-api-secret