---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: simplephone
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: simplephone-flux-secret
  url: ssh://git@github.com/afshinpaydar-binary/SimplePhone-deploy

