---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: simplephone
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./eks-prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: simplephone
  healthChecks:
    - kind: Deployment
      name: simplephone
      namespace: production

