---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: simplephone
  namespace: production
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simplephone
  targetCPUUtilizationPercentage: 80
